language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - extra-android-m2repository
  - android-26
  - sys-img-armeabi-v7a-android-17

jdk:
  - oraclejdk8

licenses:
- android-sdk-license-.+
- android-sdk-license-c81a61d9

notifications:
  email: false

sudo: false

branches:
  except:
    - gh-pages

script: ./gradlew clean build

after_success: